export const CATEGORIES = [
  {
    id: 'communication',
    num: '001',
    label: 'Communication',
    tagline: 'Stay connected without switching apps',
    integrations: [
      {
        id: 'whatsapp',
        name: 'WhatsApp',
        color: '#25D366',
        badge: 'Messaging',
        summary: 'Send and receive messages, automate reminders, and broadcast to client groups — all from within the platform.',
        bullets: [
          'Automated notifications for programs, check-ins, and reminders',
          'Two-way messaging so clients can reply directly',
          'Broadcast messages to multiple client groups at once',
          'Seamlessly connected to your automated message workflows',
        ],
      },
      {
        id: 'zoom',
        name: 'Zoom',
        color: '#2D8CFF',
        badge: 'Video calls',
        summary: 'Schedule sessions directly in SmartCoach360 and let the platform handle the meeting links and reminders.',
        bullets: [
          'Schedule and launch Zoom sessions from your coaching dashboard',
          'Meeting links sent to clients automatically',
          'Manage live session recordings in one place',
          'Host group classes and webinars with ease',
        ],
      },
      {
        id: 'teams',
        name: 'Microsoft Teams',
        color: '#6264A7',
        badge: 'Enterprise video',
        summary: 'Your coaching communications and team collaboration stay in sync without switching between platforms.',
        bullets: [
          'Conduct live coaching sessions and group calls via Teams',
          'Keep team communication and collaboration in one flow',
          'Enterprise-grade video meeting quality',
          'Automatic scheduling notifications to participants',
        ],
      },
      {
        id: 'telephony',
        name: 'Telephony',
        color: '#00FF94',
        badge: 'Phone',
        summary: 'Connect your existing phone system and manage all client calls from within SmartCoach360.',
        bullets: [
          'Click-to-call directly from client profiles',
          'Automatic call logging and history tracking',
          'Automated call reminders and follow-up sequences',
          'Works with your existing telephony infrastructure',
        ],
      },
    ],
  },
  {
    id: 'data',
    num: '002',
    label: 'Data & Forms',
    tagline: 'Keep your data where you need it',
    integrations: [
      {
        id: 'gsheets',
        name: 'Google Sheets',
        color: '#34A853',
        badge: 'Reporting',
        summary: 'Live access to your SmartCoach360 data in the format you prefer — build custom reports and share with your team.',
        bullets: [
          'Automatically export client data to Google Sheets',
          'Build custom dashboards and reports',
          'Real-time data sync so your sheets are always current',
          'Share with your team for collaborative access',
        ],
      },
      {
        id: 'gforms',
        name: 'Google Forms',
        color: '#4285F4',
        badge: 'Lead capture',
        summary: 'Capture leads and intake information through Google Forms and have them flow straight into SmartCoach360.',
        bullets: [
          'Automatic lead capture from any Google Form you create',
          'Client intake and onboarding forms that feed directly into profiles',
          'Feedback and satisfaction surveys',
          'Real-time sync to your CRM the moment someone submits',
        ],
      },
      {
        id: 'zoho',
        name: 'Zoho Forms',
        color: '#E42527',
        badge: 'Forms & surveys',
        summary: 'Your forms, surveys, and assessments connect directly with SmartCoach360, keeping all client data centralised.',
        bullets: [
          'Lead capture and client intake via Zoho Forms',
          'Survey and assessment tools for ongoing client feedback',
          'Automatic data sync to your client records',
          'Custom form workflows and trigger-based automation',
        ],
      },
    ],
  },
  {
    id: 'health',
    num: '003',
    label: 'Health & Activity',
    tagline: 'Coach from the full picture',
    integrations: [
      {
        id: 'apple',
        name: 'Apple Health',
        color: '#FC3158',
        badge: 'iOS health',
        summary: 'Steps, sleep, heart rate, and calorie data flow directly into your coaching dashboard — automatically.',
        bullets: [
          'Automatic sync of steps, activity, and heart rate data',
          'Sleep tracking and recovery data for a complete health picture',
          'Calorie and nutrition data pulled in alongside meal tracking',
          'Real-time health dashboard for evidence-based coaching',
        ],
      },
      {
        id: 'gfit',
        name: 'Google Fit / Health Connect',
        color: '#4285F4',
        badge: 'Android health',
        summary: 'The same depth of activity and health data for Android clients — every client gets the same quality of insight.',
        bullets: [
          'Activity and workout data sync in real time',
          'Calorie burn and nutrition tracking',
          'Sleep and recovery metrics',
          'Cross-platform compatibility for mixed client bases',
        ],
      },
    ],
  },
  {
    id: 'advanced',
    num: '004',
    label: 'Advanced',
    tagline: 'Beyond the basics',
    integrations: [
      {
        id: 'lab',
        name: 'Lab Integration',
        color: '#00FF94',
        badge: 'Biomarkers',
        summary: 'Incorporate biomarker and diagnostic data into client profiles alongside training and nutrition.',
        bullets: [
          'Import lab results directly into client profiles',
          'Track biomarkers and key health indicators over time',
          'Supports nutrition and wellness coaching built on clinical data',
          'Fully secure and compliant data handling',
        ],
      },
      {
        id: 'web',
        name: 'Web Content Builder',
        color: '#00FF94',
        badge: 'Lead pages',
        summary: 'Create professional lead capture pages and branded templates — no third-party tools required.',
        bullets: [
          'Drag-and-drop builder for landing pages and lead capture forms',
          'Branded email and message templates',
          'Automated lead flow from web enquiries straight into your CRM',
          'No third-party tools required',
        ],
      },
    ],
  },
]

export const SUMMARY_TABLE = [
  { name: 'WhatsApp',                 color: '#25D366', desc: 'Automated client messaging and broadcast campaigns' },
  { name: 'Zoom',                     color: '#2D8CFF', desc: 'Live session and webinar scheduling and management' },
  { name: 'Microsoft Teams',          color: '#6264A7', desc: 'Enterprise video meetings and team collaboration' },
  { name: 'Google Sheets',            color: '#34A853', desc: 'Custom reporting and live data sync' },
  { name: 'Google Forms',             color: '#4285F4', desc: 'Automated lead capture and client intake' },
  { name: 'Zoho Forms',               color: '#E42527', desc: 'Survey, assessment, and workflow automation' },
  { name: 'Apple Health',             color: '#FC3158', desc: 'Client health, activity, and recovery tracking' },
  { name: 'Google Fit / Health Connect', color: '#4285F4', desc: 'Cross-platform health data for Android users' },
  { name: 'Telephony',                color: '#00FF94', desc: 'Call management, logging, and follow-up automation' },
  { name: 'Lab Integration',          color: '#00FF94', desc: 'Biomarker and diagnostic data in client profiles' },
  { name: 'Web Content Builder',      color: '#00FF94', desc: 'Branded lead capture pages and communication templates' },
]
